<?php

namespace Creavo\MultiAppBundle\Repository;

use Creavo\MultiAppBundle\Entity\Workspace;
use Doctrine\ORM\QueryBuilder;

/**
 * AppRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppRepository extends \Doctrine\ORM\EntityRepository {

    public function getByWorkspace(Workspace $workspace) {

        /** @var QueryBuilder $qb */
        $qb=$this->createQueryBuilder('a');

        $qb
            ->andWhere('a.workspace = :workspace')
            ->setParameter('workspace',$workspace);

        return $qb;
    }

}
