<?php

namespace Creavo\MultiAppBundle\Repository;

use Creavo\MultiAppBundle\Entity\App;
use Doctrine\ORM\AbstractQuery;
use Doctrine\ORM\QueryBuilder;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends \Doctrine\ORM\EntityRepository {

    public function getQueryBuilderByApp(App $app) {

        /** @var QueryBuilder $qb */
        $qb=$this->createQueryBuilder('i');

        $qb
            ->andWhere('i.app = :app')
            ->setParameter('app',$app);

        return $qb;
    }

    public function getNextItemId(App $app) {

        /** @var QueryBuilder $qb */
        $qb=$this->createQueryBuilder('i');

        $qb
            ->select('MAX(i.itemId)')
            ->andWhere('i.app = :app')
            ->setParameter('app',$app);

        if($result=(int)$qb->getQuery()->getOneOrNullResult(AbstractQuery::HYDRATE_SINGLE_SCALAR)) {
            return $result+1;
        }

        return 1;
    }

    public function getByAppAndItemId(App $app, $itemId) {
        return $this->findOneBy([
            'app'=>$app,
            'itemId'=>$itemId,
        ]);
    }
}
